"""
BACKLOG.md projection — pure, ``typer``- and ``git``-free.

Under the operational state layer the task store (``$DT_STORE/tasks``) is the
source of truth; ``BACKLOG.md`` becomes its **projection** into the durable git
layer: "what we intend to do". This module renders that projection and keeps it
inside a marker-delimited managed block, so the surrounding hand-authored prose
(format rules, the scope-creep guard, a roadmap) is preserved.

The content is **status-independent** (design §215): it lists every *unfinished*
task — ``todo``/``doing``/``review`` intermixed, no status shown — in stable ID
order. A ``todo → doing → review`` transition changes not one byte of the file;
only creating, finishing, renaming or re-scoping a task does. This removes the
merge-conflict source of a hand-edited markdown kanban.

The git side (which branch, where the repo root is) is resolved by the Typer
wrapper in :mod:`dreamteam.backlog_cli` and passed in — this core never shells
out. ``backlog_divergence`` is built here for the future ``dt context`` (T051)
consumer; it is a pure function with no CLI of its own. See
``specs/T040-backlog-sync/spec.md``.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, NamedTuple

from dreamteam.dt.tasks import load_all_tasks

if TYPE_CHECKING:
    from pathlib import Path

    from dreamteam.dt.model import Task

# Managed-block fences. Everything between them is regenerated by `sync`;
# everything outside is untouched hand-authored prose.
BEGIN_MARKER = '<!-- dt:backlog:begin -->'
END_MARKER = '<!-- dt:backlog:end -->'

# Unfinished statuses — the backlog projects these (design §215). `done` lives
# on in CHANGELOG.md, `dropped` is abandoned; neither appears here.
_UNFINISHED = frozenset({'todo', 'doing', 'review'})

# Whole managed block, non-greedy so only the first begin→end span is replaced.
_BLOCK_RE = re.compile(
    re.escape(BEGIN_MARKER) + r'.*?' + re.escape(END_MARKER), re.DOTALL
)
# A rendered item's ID: `- **T040** — …`. Used to read a block back for divergence.
_ITEM_ID_RE = re.compile(r'\*\*(T[0-9]{3,})\*\*')


class BacklogDivergence(NamedTuple):
    """
    How far ``BACKLOG.md`` lags behind the store (for ``dt context``, T051).

    ``added`` — unfinished tasks in the store missing from the managed block
    ("created", +N). ``removed`` — IDs in the block no longer unfinished
    ("finished"/dropped, −M). Both are sorted by numeric ID.
    """

    added: list[str]
    removed: list[str]


def _id_num(task_id: str) -> int:
    """Numeric key for ``T<NNN>`` so ``T1000`` sorts after ``T200`` (not before)."""
    return int(task_id[1:])


def backlog_items(store: Path) -> list[Task]:
    """
    Unfinished task records, sorted by numeric ID (the backlog projection).

    Pure over the store — reads every record, keeps ``todo``/``doing``/``review``
    (drops ``done``/``dropped``), orders by ID ascending. Status-independent by
    construction: the set and order depend only on which tasks are unfinished.
    """
    return sorted(
        (task for task in load_all_tasks(store).values() if task.status in _UNFINISHED),
        key=lambda task: _id_num(task.id),
    )


def render_item(task: Task) -> str:
    """
    Render one task as a BACKLOG.md bullet: ID, date, title, deps, spec.

    Format (T040 §5, resolved): ``- **T040** — [2026-07-30] <title> (deps: T034;
    spec: …)``. The ``[date]`` is the record's ``created`` (omitted if unset);
    the parenthetical carries ``deps`` and ``spec``, each dropped when empty.
    """
    date = f' [{task.created.isoformat()}]' if task.created is not None else ''
    meta: list[str] = []
    if task.deps:
        meta.append(f'deps: {", ".join(task.deps)}')
    if task.spec:
        meta.append(f'spec: {task.spec}')
    tail = f' ({"; ".join(meta)})' if meta else ''
    return f'- **{task.id}** —{date} {task.title}{tail}'


def render_block(items: list[Task]) -> str:
    """
    The managed block: begin marker, one bullet per item, end marker.

    An empty store yields just the two markers (a valid, parseable empty block).
    """
    body = '\n'.join(render_item(task) for task in items)
    inner = f'\n{body}\n' if body else '\n'
    return f'{BEGIN_MARKER}{inner}{END_MARKER}'


def sync_backlog(existing_text: str, items: list[Task]) -> str:
    r"""
    Return ``existing_text`` with the managed block replaced by ``items``.

    If the markers are present, only the ``begin…end`` span is rewritten (a
    *function* replacement, so backslashes / ``\\g`` in titles are not
    interpreted). If they are absent, the block is appended at the end
    (self-bootstrap) after the existing content — nothing outside the block is
    ever touched. Idempotent: same store → byte-identical output.
    """
    block = render_block(items)
    if _BLOCK_RE.search(existing_text):
        return _BLOCK_RE.sub(lambda _: block, existing_text)
    prefix = existing_text.rstrip('\n')
    if prefix:
        return f'{prefix}\n\n{block}\n'
    return f'{block}\n'


def has_managed_block(text: str) -> bool:
    """
    True iff ``text`` contains a managed block (both markers, in order).

    Used by ``dt context`` (T051) to decide whether BACKLOG divergence is even
    meaningful: a project that has not adopted ``dt backlog sync`` has no block,
    so every store task would read as "added" — a false signal best skipped.
    """
    return _BLOCK_RE.search(text) is not None


def parse_block_ids(text: str) -> list[str]:
    """
    Task IDs listed inside the managed block of ``text`` (empty if no block).

    Only the managed span is scanned — IDs mentioned in the surrounding prose
    (a roadmap, a comment) do not count, since only the block is what ``sync``
    maintains.
    """
    match = _BLOCK_RE.search(text)
    if match is None:
        return []
    return _ITEM_ID_RE.findall(match.group(0))


def backlog_divergence(store: Path, backlog_text: str) -> BacklogDivergence:
    """
    Compare the store's unfinished set against a BACKLOG.md managed block.

    ``added`` — unfinished IDs in the store absent from the block (created since
    the last sync). ``removed`` — block IDs no longer unfinished (finished or
    dropped since the last sync). Pure: the caller supplies the file text (T051
    reads the **main working copy**, design §880). Both lists sorted by ID.
    """
    unfinished = {task.id for task in backlog_items(store)}
    in_block = set(parse_block_ids(backlog_text))
    added = sorted(unfinished - in_block, key=_id_num)
    removed = sorted(in_block - unfinished, key=_id_num)
    return BacklogDivergence(added=added, removed=removed)
